version: '3.8'

services:
  # -------------------------------------------------------------
  # 1. Spark Processing & Dev Environment (The Engine)
  # -------------------------------------------------------------
  pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: lakehouse-spark
    ports:
      - "8888:8888" # VS Code Jupyter Connection
      - "4040:4040" # Spark Web UI
    volumes:
      - ./datalake:/home/jovyan/work/datalake # Your Medallion storage
      - ./jobs:/home/jovyan/work/jobs         # Your Python/Spark scripts
      - ./dags:/home/jovyan/work/dags         # For future Airflow DAGs
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root # Prevents permission denied errors when writing files

  # -------------------------------------------------------------
  # 2. Analytical Database (Gold Layer Serving)
  # -------------------------------------------------------------
  postgres-dwh:
    image: postgres:15-alpine
    container_name: lakehouse-postgres
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_USER=data_engineer
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=logistics_analytics
    volumes:
      - pgdata:/var/lib/postgresql/data # Persists DB data
  
  # 3. The Silver Layer (Object Storage / "Cloud")
  lakehouse-minio:
    image: minio/minio:latest
    container_name: lakehouse-minio
    ports:
      - "9000:9000" # S3 API Port
      - "9001:9001" # Web UI Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    
  lakehouse-airflow:
    image: apache/airflow:2.8.1-python3.11
    container_name: lakehouse-airflow
    user: root # Required to access the Docker socket
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_DB_UPGRADE=True
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=supersecret
      - DOCKER_API_VERSION=1.44  # <--- ADD THIS LINE
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock # This lets Airflow control the Spark container
    command: >
      bash -c "apt-get update && apt-get install -y docker.io && airflow standalone"

volumes:
  pgdata:
  minio_data:
  